### ISSUE TITLE
Update schemas with testing real patient data

### ISSUE THREAD

**Issue by SenseCode** [utsw-bicf/cognitionexplorer#173]
Small adjustments when testing loading real patient data.

- [x] ivp_a3: remove momprdx, dadprdx first 0 for enums, need to repull and test
- [x] ivp_a5: delete packsper to help extract data from access database, need repull ivp_v5 and test

- [x] ivp_a4: replace medicine id start with d, need to repull and test

- [x] ivp_b5: reedit version, need to repull with right visdate format YYYY-MM-DD and test
![image](https://user-images.githubusercontent.com/38848214/113775901-f3b46200-96ee-11eb-9864-ccea50e75d3e.png)

- [x] remove extra field with instruction_b5
- [x] remove hidden field in schemas

- [x] ivp_c2: Change alert_mocatots field to object, embedded subschema, need to repull and test

- [x] ivp_d2: need to repull data, get rid of the "0+space" format and test.
- [x] ivp_z1x: need to reload and test with full Z1X version

**Comment by mingjiecn** [comment]
There is still some data field in schema ivp_a3 that has number start with 0:
![image](https://user-images.githubusercontent.com/44071821/113784885-c0c49b00-96fb-11eb-8b51-523da212dbda.png)

**Comment by mingjiecn** [comment]
For ivp_b4, need to move the number to the front for enum:
![image](https://user-images.githubusercontent.com/44071821/113786014-ec488500-96fd-11eb-9668-d8acdb0d3f80.png)

**Comment by mingjiecn** [comment]
for ivp_b8, no number key in the from of the enums:
![image](https://user-images.githubusercontent.com/44071821/113786433-bce64800-96fe-11eb-9393-59b55769cf5b.png)

**Comment by mingjiecn** [comment]
For ivp_d1 there are some extra field and  hidden fields:
![image](https://user-images.githubusercontent.com/44071821/113788396-71ce3400-9702-11eb-864e-8c31678ecc48.png)
![image](https://user-images.githubusercontent.com/44071821/113788520-b78afc80-9702-11eb-9e0f-782d79556abb.png)
This is what I identified. There should be 2 more fields that I haven't identified.

**Comment by mingjiecn** [comment]
04/07/2021:  @SenseCode , For initial forms, I re-generated all the form data except a4, b4,b8. I will work on a4 to see how to combine the two form A4D and A4G. Schema b4 and b8 need enum modification. I will wait for your change. I changed some of the schemas in order for it to work. Those changes are pushed in redcap2json project branch 28 in case you want to have a look:
https://github.com/utsw-bicf/redcap2json/tree/28-json/redcap2json/dictionary/form_schemas

**Comment by SenseCode** [comment]
Second batch test: Re-load all the IVP packets forms according to batch 1 schema adjustments, here are the result and the issues listed:
      
- [x]    1. Adjust ivp_z1x order, 4a>4b>4c. pass.
- [x] 	  2. Remove instruction_b5 field in ivp_b5. pass.
- [x] 	  3. Change visitnum in mixins.json , format must be three numbers.
- [x] 	  4. Ivp_a3:  remove ..040… 0 before in all the sibpdx fields. pass.
- [x] 	  5. Ivp_a1, ivp_a2 reload  >>>> all pass.
- [x] 	  6. Ivp_a4: missing form data. (Medicine chart), need to repull and test.
- [x] 	  7. Ivp_a5: reload result showed 92/103 loaded.  Fields order messed up, remove note_a5, need to repull and test.
![image](https://user-images.githubusercontent.com/38848214/114882574-b2e0db00-9dc9-11eb-9c91-660298cd3d3d.png)

- [x]   8. I vp_b5: Change formver from 3.1>>>3.10, need to discuss with collaborator and Mingjie.
- [x] 	  9. Ivp_c2: Validation failed.  No any extra fields /Hidden fields found, need to repull and test.
![image](https://user-images.githubusercontent.com/38848214/114882804-f3405900-9dc9-11eb-823f-0d85d0d4c786.png)

- [x] 	  10.  Ivp_d2: reload and pass. 
- [x] 	  11.Ivp_b1, b6, b7, b9 reload and all pass
- [x] 	  12. Ivp_d1: change note_d1_11 to subschema. Need to repull and reload for test.
- [x]     13. Only one hidden field in ivp_d1, leave it for now for retest, wait for the adjustment for hidden fields based on versions.
- [x] 	  14.  Search all fields for descriptions, and remove.
- [x]    15. switch `text - number` with `number - text `in ivp_b4 to avail mapping.(I recalled changed this before),need to reload and test.
![image](https://user-images.githubusercontent.com/38848214/114200363-be8c5780-991a-11eb-920d-3d6fd6f9cc24.png)

- [x]    16.  Add numbers in version1/2 fields in ivp_b8. But these are hidden fields.Leave them for now. Need to reload and test.
-![image](https://user-images.githubusercontent.com/38848214/114200445-d5cb4500-991a-11eb-8fd7-b1226bb343a4.png)

**Comment by SenseCode** [comment]
- [x] remove hidden fields in ivp_b8
- [x] remove hidden fields in ivp_d1
- [x] remove hidden field in ivp_b9, need to repull and test.

**Comment by mingjiecn** [comment]
Data generated on 4/12/2021: **ivp_a4, ivp_a5, ivp_d1, ivp_b4, ivp_b8**.

for ivp_c2, looks like the schema needs to be fix to allow value "996":
![image](https://user-images.githubusercontent.com/44071821/114462847-3ec7ec80-9ba9-11eb-98c0-cb0053dffef8.png)
![image](https://user-images.githubusercontent.com/44071821/114462860-45566400-9ba9-11eb-9be3-76703dac7d3c.png)
![image](https://user-images.githubusercontent.com/38848214/114883117-3b5f7b80-9dca-11eb-85f7-0e63455fa886.png)



The enum list - [0.0, 0.5, 1.0, 2.0, 3.0] for cdrglob in ivp_b4 is different than the data submitted to NACC - [0, 0.5, 1, 2, 3].  I changed the schema at local so I can generate the data for ivp_b4.
![image](https://user-images.githubusercontent.com/44071821/114462935-5b642480-9ba9-11eb-9d0c-4509f46479a6.png)
![image](https://user-images.githubusercontent.com/44071821/114898950-2d185c00-9dd8-11eb-9f48-262267b18299.png)

**Comment by SenseCode** [comment]
- [x] Edit ivp_c2 trailb_c2 field pattern.
- [x] rewrite ivp_b4 with new mapping number

**Comment by SenseCode** [comment]
Third batch and four batch(ivp_c2, ivp_b4) test:

- [x] Ivpb8 edit schema, pass
- [x] ivp_d1 pass
- [x] ivp_b5 removed required fields, edit pattern, pass
- [x] ivp_c2 pass with new schema
- [x] ivp_b4 pass with new schema
- [x] ivp_a4: non listed drugs order fields listed as listed drugid, failed to load some of the real data, need to reextract and retest.
![image](https://user-images.githubusercontent.com/38848214/114630360-06dfa880-9c80-11eb-8bd8-dca8fda241ec.png)

**Comment by SenseCode** [comment]
- [x] Retest ivp_a4 and failed, need to reextract and retest with subschema format after `drugid_31`
![image](https://user-images.githubusercontent.com/38848214/114742966-d6e0e580-9d11-11eb-8ad7-318694286720.png)

**Comment by SenseCode** [comment]
- [x] Retest ivp_a4, pass. ( All ivp packets passed so far. )

**Comment by SenseCode** [comment]
FVP packets testing issues:

- [x] fvp_d2, change string fields to boolean fields, need to repull and test.
- [x] change fvp_a1, required field, pass.
- [x] change fvp_a2 required field and pattern, pass
- [x] Edit fvp_a3 schema, remove nonsense 0 from druglist, need to repull and retest
- [x] fvp_b1 pass
- [x] fvp_b5, b6,b7 remove required fields, pass
- [x] fvp_b8 pass
- [x] fvp_b9: remove required fields, 626/627 pass. One real data cannot fit pattern need to QA with collaborator. 
![image](https://user-images.githubusercontent.com/38848214/115046227-d759b780-9e9c-11eb-838c-94b90aacbea3.png)
![image](https://user-images.githubusercontent.com/38848214/115052739-e859f700-9ea3-11eb-9ffb-15476d1f70f5.png)
![image](https://user-images.githubusercontent.com/38848214/115052699-dd06cb80-9ea3-11eb-8d04-ee9577315abc.png)

- [x] fvp_c2, pass
- [x] fvp_d1: change question 8-10 mapping number 8>>9, need to repull and test

- [x] fvp_b4: update new schema with correct mapping numbers, need to repull and test.
- [x] fvp_a4: replace schema first number with d in drug list, need to repull and test.

**Comment by SenseCode** [comment]
- [x] update fvp_z1x order.

**Comment by mingjiecn** [comment]
20210416: uploaded new data files shown in the screen shot below. 
![image](https://user-images.githubusercontent.com/44071821/115077010-fcf9b780-9ec2-11eb-8e86-6fcf29c55008.png)

**Comment by SenseCode** [comment]
Third batch Fvp packets testing result:

- [x] Fvp_a3: 626/627 loaded, need to check the original data and make sure this is it...
![image](https://user-images.githubusercontent.com/38848214/115404403-e8fbd180-a1b2-11eb-85a2-9a555dc363b9.png)

- [x] fvp_b4, fvp_d1, fvp_d2, fvp_a4 all passed with our updated schemas.

**Comment by SenseCode** [comment]
- [x] fvp_b9: 626/627 pass. One real data cannot fit pattern need to double check and  QA. 
![image](https://user-images.githubusercontent.com/38848214/115405299-bdc5b200-a1b3-11eb-8d87-070902288f37.png)
![image](https://user-images.githubusercontent.com/38848214/115052739-e859f700-9ea3-11eb-9ffb-15476d1f70f5.png)
![image](https://user-images.githubusercontent.com/38848214/115052699-dd06cb80-9ea3-11eb-8d04-ee9577315abc.png)

**Comment by SenseCode** [comment]
m1 form real patient data test issue:

- [x] 236/256 m1 loaded, need to repull and  retest
m1_initials doesn't exist in schema, note_mlstn_type field value doesn't fit.
![image](https://user-images.githubusercontent.com/38848214/115733122-35c7df80-a34e-11eb-823c-b41f3c3612e4.png)

![image](https://user-images.githubusercontent.com/38848214/115733916-edf58800-a34e-11eb-8188-20fb74666b62.png)

**Comment by SenseCode** [comment]
M1 form real data was reloaded and passed with the updated file. Cannot find the M1 version3 template form, need to ask collaborator.

**Comment by SenseCode** [comment]
- [x]  Rewrite M1 schema with version 3 template, need to repull and test.
