### ISSUE TITLE
Change Date to be one field instead of 3 fields

### ISSUE THREAD

**Issue by vsmalladi** [utsw-bicf/cognitionexplorer#35]

**Comment by vsmalladi** [comment]
https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates

**Comment by SenseCode** [comment]
Cannot effectively filtering year and month format when using calendar format "YYYY-MM". Only date and date time work in Json schema draft 4. Need to see how we arrange in the future. Currently keep the birth year and birth month format.
