### ISSUE TITLE
Change redcap form ivp_d1, some questions' options with format: number+space+text

### ISSUE THREAD

**Issue by SenseCode** [utsw-bicf/cognitionexplorer#93]
![image](https://user-images.githubusercontent.com/38848214/100662399-76c94400-331a-11eb-9322-35d4247235e7.png)
![image](https://user-images.githubusercontent.com/38848214/100662424-7b8df800-331a-11eb-9c30-928aa6d6b493.png)

Answer should be:
6a-6j:  0 No, 1 Yes, 8 Unknown, not accessed
6k: 0 No, 1 Yes
7a-7f: 0 No, 1 Yes, 8 Unknown/not accessed

**Comment by jay-gates** [comment]
Fixed in REDCap.
